### ISSUE TITLE
Unable to pull links from subsequent pages.

### ISSUE THREAD

**Issue by frdbonif** [UKSquire/BBCiPlayer#1]
The program is not able to pull links from any additional pages.

For example:
```
BBC-iplayer https://www.bbc.co.uk/iplayer/episodes/m0009tgy/bing?seriesId=b046ts1d&page=2
https://www.bbc.co.uk/iplayer/episode/b046thg1/bing-series-1-1-fireworks
https://www.bbc.co.uk/iplayer/episode/b046ts21/bing-series-1-2-bye-bye
https://www.bbc.co.uk/iplayer/episode/b046tt7g/bing-series-1-3-swing
https://www.bbc.co.uk/iplayer/episode/b046tys2/bing-series-1-4-blocks
https://www.bbc.co.uk/iplayer/episode/b046v07p/bing-series-1-5-ducks
https://www.bbc.co.uk/iplayer/episode/b046sdsq/bing-series-1-6-smoothie
https://www.bbc.co.uk/iplayer/episode/b047cz86/bing-series-1-7-frog
https://www.bbc.co.uk/iplayer/episode/b047d5qk/bing-series-1-8-car-park
https://www.bbc.co.uk/iplayer/episode/b047d659/bing-series-1-9-shadow
https://www.bbc.co.uk/iplayer/episode/b047d4q3/bing-series-1-10-musical-statues
https://www.bbc.co.uk/iplayer/episode/b047wtlv/bing-series-1-11-voo-voo
https://www.bbc.co.uk/iplayer/episode/b047zrfs/bing-series-1-12-here-i-go
https://www.bbc.co.uk/iplayer/episode/b047zwxm/bing-series-1-13-growing
https://www.bbc.co.uk/iplayer/episode/b0480276/bing-series-1-14-atchoo
https://www.bbc.co.uk/iplayer/episode/b048065z/bing-series-1-15-hideandseek
https://www.bbc.co.uk/iplayer/episode/b048sj6w/bing-series-1-16-bake
https://www.bbc.co.uk/iplayer/episode/b048sjp5/bing-series-1-17-train
https://www.bbc.co.uk/iplayer/episode/b048sjy6/bing-series-1-18-say-goodbye
https://www.bbc.co.uk/iplayer/episode/b048slzg/bing-series-1-19-lost
https://www.bbc.co.uk/iplayer/episode/b048sq0k/bing-series-1-20-picnic
https://www.bbc.co.uk/iplayer/episode/b04h8ky8/bing-series-1-21-balloon
https://www.bbc.co.uk/iplayer/episode/b04h8nrd/bing-series-1-22-dressing-up
https://www.bbc.co.uk/iplayer/episode/b04hc036/bing-series-1-23-something-for-sula
https://www.bbc.co.uk/iplayer/episode/b04hc2x1/bing-series-1-24-knack
https://www.bbc.co.uk/iplayer/episode/b04hd14h/bing-series-1-25-hearts
https://www.bbc.co.uk/iplayer/episode/b04hztqd/bing-series-1-26-storytime
https://www.bbc.co.uk/iplayer/episode/b04j2g6j/bing-series-1-27-giving
https://www.bbc.co.uk/iplayer/episode/b05tk9f8/bing-series-1-27-nature-explorer
https://www.bbc.co.uk/iplayer/episode/b04j2mnv/bing-series-1-28-hula-hoop
https://www.bbc.co.uk/iplayer/episode/b05tkbvw/bing-series-1-28-choosing
https://www.bbc.co.uk/iplayer/episode/b04j2nzb/bing-series-1-29-big-boots
https://www.bbc.co.uk/iplayer/episode/b04j33jk/bing-series-1-30-bubbles
https://www.bbc.co.uk/iplayer/episode/b04jqs52/bing-series-1-31-paddling-pool
https://www.bbc.co.uk/iplayer/episode/b04jrv7c/bing-series-1-32-blankie
https://www.bbc.co.uk/iplayer/episode/b04jrwr6/bing-series-1-33-boo
https://www.bbc.co.uk/iplayer/episode/b04jry2q/bing-series-1-34-talkie-taxi
'page' is not recognized as an internal or external command,
operable program or batch file.
```

Is there a fix that can be made in software or an alternative URL format that can be used to pull data from subsequent pages.  Obviously the number of programs with more than one page per series is fairly limited.

**Comment by UKSquire** [comment]
The issue is caused by the command line shell taking "&" as "also run this additional program.

If you call the BBC-Iplayer from within a .cmd, and escape this character, it will work fine.

For example:

Create a file called "bing.cmd"

Write these lines:
@echo off
bbc-iplayer https://www.bbc.co.uk/iplayer/episodes/m0009tgy/bing?seriesId=b046ts1d^&page=1
bbc-iplayer https://www.bbc.co.uk/iplayer/episodes/m0009tgy/bing?seriesId=b046ts1d^&page=2
bbc-iplayer https://www.bbc.co.uk/iplayer/episodes/m0009tgy/bing?seriesId=b046ts1d^&page=3

Save this, and now just type "bing" at the command prompt:

https://www.bbc.co.uk/iplayer/episode/b046thg1/bing-series-1-1-fireworks
https://www.bbc.co.uk/iplayer/episode/b046ts21/bing-series-1-2-bye-bye
https://www.bbc.co.uk/iplayer/episode/b046tt7g/bing-series-1-3-swing
https://www.bbc.co.uk/iplayer/episode/b046tys2/bing-series-1-4-blocks
https://www.bbc.co.uk/iplayer/episode/b046v07p/bing-series-1-5-ducks
https://www.bbc.co.uk/iplayer/episode/b046sdsq/bing-series-1-6-smoothie
https://www.bbc.co.uk/iplayer/episode/b047cz86/bing-series-1-7-frog
https://www.bbc.co.uk/iplayer/episode/b047d5qk/bing-series-1-8-car-park
https://www.bbc.co.uk/iplayer/episode/b047d659/bing-series-1-9-shadow
https://www.bbc.co.uk/iplayer/episode/b047d4q3/bing-series-1-10-musical-statues
https://www.bbc.co.uk/iplayer/episode/b047wtlv/bing-series-1-11-voo-voo
https://www.bbc.co.uk/iplayer/episode/b047zrfs/bing-series-1-12-here-i-go
https://www.bbc.co.uk/iplayer/episode/b047zwxm/bing-series-1-13-growing
https://www.bbc.co.uk/iplayer/episode/b0480276/bing-series-1-14-atchoo
https://www.bbc.co.uk/iplayer/episode/b048065z/bing-series-1-15-hideandseek
https://www.bbc.co.uk/iplayer/episode/b048sj6w/bing-series-1-16-bake
https://www.bbc.co.uk/iplayer/episode/b048sjp5/bing-series-1-17-train
https://www.bbc.co.uk/iplayer/episode/b048sjy6/bing-series-1-18-say-goodbye
https://www.bbc.co.uk/iplayer/episode/b048slzg/bing-series-1-19-lost
https://www.bbc.co.uk/iplayer/episode/b048sq0k/bing-series-1-20-picnic
https://www.bbc.co.uk/iplayer/episode/b04h8ky8/bing-series-1-21-balloon
https://www.bbc.co.uk/iplayer/episode/b04h8nrd/bing-series-1-22-dressing-up
https://www.bbc.co.uk/iplayer/episode/b04hc036/bing-series-1-23-something-for-sula
https://www.bbc.co.uk/iplayer/episode/b04hc2x1/bing-series-1-24-knack
https://www.bbc.co.uk/iplayer/episode/b04hd14h/bing-series-1-25-hearts
https://www.bbc.co.uk/iplayer/episode/b04hztqd/bing-series-1-26-storytime
https://www.bbc.co.uk/iplayer/episode/b04j2g6j/bing-series-1-27-giving
https://www.bbc.co.uk/iplayer/episode/b04j2mnv/bing-series-1-28-hula-hoop
https://www.bbc.co.uk/iplayer/episode/b04j2nzb/bing-series-1-29-big-boots
https://www.bbc.co.uk/iplayer/episode/b05tkmxc/bing-series-1-29-dark
https://www.bbc.co.uk/iplayer/episode/b04j33jk/bing-series-1-30-bubbles
https://www.bbc.co.uk/iplayer/episode/b04jqs52/bing-series-1-31-paddling-pool
https://www.bbc.co.uk/iplayer/episode/b04jrv7c/bing-series-1-32-blankie
https://www.bbc.co.uk/iplayer/episode/b04jrwr6/bing-series-1-33-boo
https://www.bbc.co.uk/iplayer/episode/b04jry2q/bing-series-1-34-talkie-taxi
https://www.bbc.co.uk/iplayer/episode/b04jrybn/bing-series-1-35-kite
https://www.bbc.co.uk/iplayer/episode/b04k6fjq/bing-series-1-36-more
https://www.bbc.co.uk/iplayer/episode/b04kkc5t/bing-series-1-37-sparkle-magic
https://www.bbc.co.uk/iplayer/episode/b04kkkc6/bing-series-1-38-tree
https://www.bbc.co.uk/iplayer/episode/b04kkkz3/bing-series-1-39-wheres-flop
https://www.bbc.co.uk/iplayer/episode/b04kkmjt/bing-series-1-40-lunchbox
https://www.bbc.co.uk/iplayer/episode/b04pwgkf/bing-series-1-41-sleepover
https://www.bbc.co.uk/iplayer/episode/b04q0g8k/bing-series-1-42-surprise-machine
https://www.bbc.co.uk/iplayer/episode/b04q0gff/bing-series-1-43-dizzy
https://www.bbc.co.uk/iplayer/episode/b04q0kcn/bing-series-1-44-house
https://www.bbc.co.uk/iplayer/episode/b04q0l1p/bing-series-1-45-ice-lolly
https://www.bbc.co.uk/iplayer/episode/b04t60zp/bing-series-1-46-mural
https://www.bbc.co.uk/iplayer/episode/b04t65y5/bing-series-1-47-hiding
https://www.bbc.co.uk/iplayer/episode/b04t6f9k/bing-series-1-48-sandcastle
https://www.bbc.co.uk/iplayer/episode/b04t6m0d/bing-series-1-49-acorns
https://www.bbc.co.uk/iplayer/episode/b04t6pqb/bing-series-1-50-jingly-shoes
https://www.bbc.co.uk/iplayer/episode/b04tr83c/bing-series-1-51-looking-after-flop
https://www.bbc.co.uk/iplayer/episode/b04ttd0x/bing-series-1-52-music
https://www.bbc.co.uk/iplayer/episode/b04ttf5z/bing-series-1-53-hippity-hoppity-voosh
https://www.bbc.co.uk/iplayer/episode/b04tthmf/bing-series-1-55-come-on-charlie
https://www.bbc.co.uk/iplayer/episode/b04v5hhp/bing-series-1-56-skateboard
https://www.bbc.co.uk/iplayer/episode/b04v5ls1/bing-series-1-57-butterfly
https://www.bbc.co.uk/iplayer/episode/b04v5nhs/bing-series-1-58-chalk-dinosaur
https://www.bbc.co.uk/iplayer/episode/b05sxwv8/bing-series-1-62-plasters
https://www.bbc.co.uk/iplayer/episode/b05sxxpt/bing-series-1-63-cat
https://www.bbc.co.uk/iplayer/episode/b05sxyhp/bing-series-1-64-dandelion
https://www.bbc.co.uk/iplayer/episode/b05sxzgc/bing-series-1-65-voosh
https://www.bbc.co.uk/iplayer/episode/b05tk9f8/bing-series-1-66-nature-explorer
https://www.bbc.co.uk/iplayer/episode/b05tkbvw/bing-series-1-67-choosing
https://www.bbc.co.uk/iplayer/episode/b05tkpc3/bing-series-1-69-stuck
https://www.bbc.co.uk/iplayer/episode/b05tkr1s/bing-series-1-70-cake
https://www.bbc.co.uk/iplayer/episode/b05vhbgk/bing-series-1-71-not-yours
https://www.bbc.co.uk/iplayer/episode/b05vhc06/bing-series-1-72-mine
https://www.bbc.co.uk/iplayer/episode/b05vhd2w/bing-series-1-73-lunch
https://www.bbc.co.uk/iplayer/episode/b05vhdqs/bing-series-1-74-woof
https://www.bbc.co.uk/iplayer/episode/b05vhfnx/bing-series-1-75-eggy-head
https://www.bbc.co.uk/iplayer/episode/b05w8l4v/bing-series-1-76-toy-party
https://www.bbc.co.uk/iplayer/episode/b05w8lkb/bing-series-1-77-mobile-phone
https://www.bbc.co.uk/iplayer/episode/b05w8m0d/bing-series-1-78-show
